apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: static-ingress
 namespace: upright
spec:
 rules:
 - host: testing.<hostname>
   http:
     paths:
     - path:
       backend:
         serviceName: static-svc
         servicePort: 80
